name: Ubuntu-Clang

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        except: [1, 0]
        pic: [1, 0]
        rtti: [1, 0]
    steps:
    - uses: actions/checkout@v2

    - name: Setup Clang
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-15 lld-15 libc++-15-dev libc++abi-15-dev

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-fno-exceptions=${{ matrix.except }} -fPIC=${{ matrix.pic }} -fno-rtti=${{ matrix.rtti }}" ..
        make -j2

    - name: Test
      run: |
        cd build
        ctest -j2