name: Ubuntu-GCC-Sanitizer

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup GCC
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ libc++-dev libc++abi-dev

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release -DENABLE_THREAD_SANITIZER=ON -DBUILD_BENCHMARKS=OFF -DCMAKE_CXX_FLAGS="-fsanitize=thread -fno-omit-frame-pointer -g" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=thread" ..
        make -j2

    - name: Test
      run: |
        cd build
        ctest -j2